theme: jekyll-theme-cayman
title: [Venkat Veerappan]
description: <img src="https://venkatvv.github.io/venkat.JPG" alt="Profile" style="border-radius:50%; height:300px;"/> <br> Software & Game Developer