theme: jekyll-theme-cayman
title: [Venkat Veerappan]
<img src="http://venkatvv.github.io/venkat_img.jpg" alt="Profile" style="border-radius:50%; height: 200px; width: 50%;"/>
description: Software Developer & Game Developer